### ISSUE TITLE
Tenant(, public, public) | What caused the crash: Unable to create the directory

### ISSUE THREAD

**Issue by adiii717** [supertokens/supertokens-docker-postgresql#24]
Docker image
```
registry.supertokens.io/supertokens/supertokens-postgresql:6.0
```
docker-compose
```yaml
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:6.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - 'stack'
    environment:
      POSTGRESQL_USER: '${POSTGRES_USER}'
      POSTGRESQL_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRESQL_DATABASE_NAME: '${POSTGRES_DB}'
      POSTGRESQL_TABLE_NAMES_PREFIX: 'supertokens'
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      API_KEYS: '${SUPERTOKENS_API_KEY}'
      ACCESS_TOKEN_BLACKLISTING: 'true'
```

**Logs:**

```
24 Jul 2023 08:49:05:793 +0000 | INFO | pid: 3f7ed4ef-eb4e-439b-b9a8-268787eb0d3c | [main] thread | io.supertokens.cronjobs.CronTask.shutdownIsGoingToBeCalled(CronTask.java:72) | Tenant(, public, public) | Stopping task: DeleteExpiredAccessTokenSigningKeys

24 Jul 2023 08:49:07:128 +0000 | INFO | pid: 3f7ed4ef-eb4e-439b-b9a8-268787eb0d3c | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:167) | Tenant(, public, public) | Cronjob finished: Telemetry

Tenant(, public, public) | What caused the crash: Unable to create the directory [/usr/lib/supertokens/webserver-temp/dc248361-d7dd-4a7b-8266-10cfb0465027] to use as the base directory
```
