### ISSUE TITLE
"Error connecting to PostgreSQL instance" when starting supertokens-postgresql:9.2.0

### ISSUE THREAD

**Issue by jletroui** [supertokens/supertokens-docker-postgresql#46]
## 🐛 Bug Report

Following instructions [from the documentation](https://supertokens.com/docs/emailpassword/pre-built-ui/setup/core/with-docker), cannot start ` supertokens-postgresql`.

### Reproduction steps:

Following docker compose:

```yaml
services:
  postgres_svc:
    container_name: go_postgres_ctnr
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
        - 5432:5432
    volumes:
      - ./db/db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'secret']
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens_svc:
    container_name: go_supertokens_ctnr
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.2.0
    depends_on:
      postgres_svc:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens:supertokens@postgres_svc:5432/supertokens"
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
```

With following `db/db-init/db-init.sql` db init file:

```sql
CREATE USER supertokens WITH PASSWORD 'supertokens';
CREATE DATABASE supertokens;
```

### Observed behaviour

Fails with the following:

```
$ docker logs -f go_supertokens_ctnr
Loading supertokens config.
Loading supertokens version.yaml file.
Completed config.yaml loading.
Loading storage layer.
Loading PostgreSQL config.
28 Aug 2024 17:09:35:173 +0000 | INFO | pid: b64ce222-01d4-4588-8600-7a891aef35d5 | [main] thread | io.supertokens.storage.postgresql.ConnectionPool.initPool(ConnectionPool.java:157) | Setting up PostgreSQL connection pool.

Setting up PostgreSQL connection pool.
28 Aug 2024 17:09:35:214 +0000 | ERROR | pid: b64ce222-01d4-4588-8600-7a891aef35d5 | [main] thread | io.supertokens.storage.postgresql.HikariLoggingAppender.doAppend(HikariLoggingAppender.java:132) | |localhost|5432|supertokens|public~|10|allowPublicKeyRetrieval=true|postgresql|60000 - Exception during pool initialization.

28 Aug 2024 17:09:35:215 +0000 | INFO | pid: b64ce222-01d4-4588-8600-7a891aef35d5 | [main] thread | io.supertokens.storage.postgresql.ConnectionPool.initPool(ConnectionPool.java:184) | Error connecting to PostgreSQL instance. Please make sure that PostgreSQL is running and that you have specified the correct values for ('postgresql_host' and 'postgresql_port') or for 'postgresql_connection_uri'

Error connecting to PostgreSQL instance. Please make sure that PostgreSQL is running and that you have specified the correct values for ('postgresql_host' and 'postgresql_port') or for 'postgresql_connection_uri'
28 Aug 2024 17:09:35:216 +0000 | INFO | pid: b64ce222-01d4-4588-8600-7a891aef35d5 | [main] thread | io.supertokens.storage.postgresql.ConnectionPool.initPool(ConnectionPool.java:188) | Trying again in a few seconds for 60.0 mins...

Trying again in a few seconds for 60.0 mins...
```

It seems supertokens is ignoring the `postgresql_connection_uri` and is trying to connect to `localhost` instead.

### Expected behaviour

The `postgresql_connection_uri` setting in the config file should be honoured.

## Useful informations

Config file seems correct:

```
$ docker exec -it go_supertokens_ctnr cat /usr/lib/supertokens/config.yaml | grep postgres
postgresql_config_version: 0
# postgresql_connection_pool_size:
# following format: postgresql://[user[:[password]]@]host[:port][/dbname][?attr1=val1&attr2=val2...
# postgresql_connection_uri:
# (DIFFERENT_ACROSS_TENANTS | OPTIONAL | Default: "localhost") string value. Specify the postgresql host url here.
# postgresql_host:
# postgresql_port:
# ability to create new tables. To see the tables needed, visit: https://supertokens.com/docs/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql
# postgresql_user:
# postgresql_password:
# postgresql_database_name:
# postgresql_table_schema:
# postgresql_table_names_prefix:
# postgresql_key_value_table_name:
# postgresql_session_info_table_name:
# postgresql_emailpassword_users_table_name:
# postgresql_emailpassword_pswd_reset_tokens_table_name:
# postgresql_emailverification_tokens_table_name:
# postgresql_emailverification_verified_emails_table_name:
# postgresql_thirdparty_users_table_name:
# postgresql_idle_connection_timeout:
# postgresql_minimum_idle_connections:
postgresql_connection_uri: postgresql://supertokens:supertokens@postgres_svc:5432/supertokens
```

Enforcing the config file location in the docker compose service specification does not change the behaviour. Ex:

```
    command: "supertokens start --with-config=/usr/lib/supertokens/config.yaml"
```
